### PR TITLE
Add promise.prototype.finally support

### PR DESCRIPTION
**Pull request by notgiorgi**
Contributing to #124 

This is still a draft, doc an test updates are still needed. Let's review this first.

I added `dispatchFinallyAction` as flag in config, which defaults to false, in the future, if `Promise.prototype.finally` gets in standard we could change it.

### CODE REVIEW

**Comment by pburtchaell** [comment]
Awesome! I'll take a deeper look at this later this week. Just after an initial glance, I like the change to the `getAction` function. 👍

**Comment by pburtchaell** [comment]
I just reviewed this and I think the implementation is good.

One consideration to make, however, is **when** the middleware will dispatch a "finally" action. To dispatch a finally action for every promise would create a lot of noise. Finally 

There are cases where a finally action is useful for cleanup. For example, I have an async action that makes an HTTP request. The **pending** action shows a loading spinner and the **finally** action hides the loading spinner, regardless of the settled promise state.

The more I think about this implementation, the more I wonder if the middleware should handle it at all. Perhaps the best use of `promise.finally` is at the action creator.

```js
const fooActionCreator = () => {
  return dispatch => {

    return dispatch({
      type: 'FOO',
      payload: new Promise()
    }).finally(() => {
      // cleanup
    });
  };
}
```

**Comment by notgiorgi** [comment]
@pburtchaell Fair point.

Maybe we could provide a flag in `meta` property of an action, like `meta.dispatchFinally` or something like that.

**Comment by tomatau** [comment]
What will the error semantics be?

Sometimes async action creators can swallow errors, like when a component updates and throws because of a state change. This gets confusing if it throws inside a `finally` as the finally is in-fact a new promise and so will need another catch block.

**Comment by pburtchaell** [comment]
Thanks for your work here @notgiorgi! I'm going to close this (along with #124) because think it's probably best if we leave this alone for now. We can reopen if there is a need for it.

**Comment by notgiorgi** [comment]
How should I proceed?

**Comment by pburtchaell** [comment]
Hey @notgiorgi! Right now [the proposal for `promise.prototype.finally`](https://github.com/tc39/proposal-promise-finally) is in Stage 2 of the [process](https://tc39.github.io/process-document/), which means it's still experimental and changes will likely occur. 

As such, I think it's best if we don't support this feature—since it will likely change—until Stage 3, and that would require extra maintenance on our end. 

What do you think? Are you actually using `promise.finally` right now?

**Comment by notgiorgi** [comment]
I agree with you, we should probably wait at least till stage 3.

I use it in nodejs, bluebird library provides it, but it's not really crucial thing so we can wait.

**Comment by notgiorgi** [comment]
finally advanced to stage 3: https://github.com/tc39/proposal-promise-finally

**Comment by pburtchaell** [comment]
@notgiorgi I've been thinking about how finally fits into this middleware and I'm not sure it makes sense to dispatch an action for finally. It seems redundant—like dispatching an action for `Promise.prototype.then`. What do you think?

**Comment by tomatau** [comment]
It could be useful for integrations with sagas or observables that would like to perform cleanup of transactions after either reject or resolve.

I don't think it has many use cases and it could be misused quite easily, but still, it would have value.

**Comment by notgiorgi** [comment]
> It could be useful for integrations with sagas or observables that would like to perform cleanup of transactions after either reject or resolve.

That's exactly what I'm aiming for.

> It seems redundant—like dispatching an action for Promise.prototype.then. What do you think?

What do you mean by that? we are already dispatching for `then` and `catch`

**Comment by pburtchaell** [comment]
Sorry for the delay here—spent the last two weeks finishing up my last job and moving.

To revisit my first comment here:
> I'm not sure it makes sense to dispatch an action for finally

What I meant is I don't believe we should dispatch `YOUR_ACTION_FINALLY` alongside `YOUR_ACTION_PENDING` and `YOUR_ACTION_FULFILLED/REJECTED`. 

Why?

We know (1) actions describe changes to the Redux state tree and (2) Promises are state machines. A promise can be in one of two states: pending and settled—the settled state being either rejected or fulfilled. One of my design principles for this middleware is to dispatch actions that describe the promise state. Therefore, it always dispatches two actions for every promise: one for the pending state and one for the respective settled state.

As I thought about how to implement support for finally, I didn't think it fit into that design principle.  Finally isn't a promise state. It would be like dispatching an action for `then` or `catch`, no?

Do you agree?

[As I mentioned earlier in the year](https://github.com/pburtchaell/redux-promise-middleware/pull/142#issuecomment-274347595), can `finally` just be used in the action creator?

```js
const fooActionCreator = () => {
  return dispatch => {

    return dispatch({
      type: 'FOO',
      payload: new Promise()
    }).finally(() => {
      // cleanup
    });
  };
}
```

**Comment by pburtchaell** [comment]
Also reopening this since it is under discussion. ✨

**Comment by notgiorgi** [comment]
Okay, now I see, you're right.

**Comment by pburtchaell** [comment]
Cool—just want to make sure we think through major changes like this! Thanks for your work on the PR and for helping with this.

**Pull request closed without merging**
