### PR TITLE
Rethrow originally caught error in handleReject

### PR DESCRIPTION
**Pull request by ianks**
See: https://github.com/pburtchaell/redux-promise-middleware/pull/101.
Resolves: #104.

### CODE REVIEW

**Comment by ianks** [comment]
This will prob require a new major release since the reject API has changed. @pburtchaell, let me know about your thoughts on creating the documentation for that.

**Comment by pburtchaell** [comment]
Thanks @ianks. I will take a look this week.

**Comment by ianks** [comment]
Sounds good. As a note, I am currently using this branch in production and it seems to be working great! Having proper error messages is a huge win for development.

**Comment by pburtchaell** [comment]
@ianks I reviewed this tonight and I think we should be able to merge. I'll do this tomorrow when I have time to write the release notes. 😄

**Comment by pburtchaell** [comment]
We (or I) will also need to update the documentation and README before releasing this.

**Comment by ianks** [comment]
@pburtchaell Either way is fine with. It might be better if you handle the documentation since I cannot do it tomorrow; otherwise I could do it Wednesday.

**Comment by Imior** [comment]
Hi, is there any precise release date? 
Right now, guess I can only solve this problem by copying source code to my repo :(

**Comment by pburtchaell** [comment]
@Imior, instead of copying the source code, It is possible to have npm install a specific branch on a repo. Checkout the npm documentation.

As far as release date, I'd like to say possibly today, but this weekend at the latest.

**Comment by ianks** [comment]
hey @Imior I am using this in my package.json

```
"redux-promise-middleware": "https://s3-us-west-1.amazonaws.com/adhawk-random-public/redux-promise-middleware-4.0.0.tgz",
```

**Comment by Imior** [comment]
Thanks for replies~ @pburtchaell  @ianks 

I've tried to use Github urls as dependencies, for example:
```
"redux-promise-middleware": pburtchaell/redux-promise-middleware#a68cd97136ad42fee68b15849745f34cdda4ffdd
```
Maybe be because of  `.npmingore`, there is not `dist` or `src` directories :



Do I have to install from built files served by myself?

**Comment by ianks** [comment]
the library has to be built, you can just use the tarball that I linked
earlier

**Comment by Imior** [comment]
@ianks ok, thanks a lot~

**Comment by pburtchaell** [comment]
This is released as `redux-promise-middleware@4.0.0`. Thanks! 😄

**Pull request merged**
