### PR TITLE
Don't copy false values. Fixes usage in React Native.

### PR DESCRIPTION
**Pull request by steida**
https://github.com/facebook/react-native/blob/6a838a4201f99ae5e88b3684bb
798d363815dd53/packager/react-packager/src/Resolver/polyfills/polyfills.
js#L24

### CODE REVIEW

**Comment by pburtchaell** [comment]
Thanks. I will review this later this week when I have some time to. cc/ @tomatau

**Comment by tomatau** [comment]
Hi @steida the link you posted is broken. Any chance you could submit a currently failing test for this?

**Comment by steida** [comment]
Fixed link: https://github.com/facebook/react-native/blob/master/packager/react-packager/src/Resolver/polyfills/polyfills.js#L19

It's hard to add failing test because React Native uses its own optimized Object.assign. Check the link. You code is technically correct, it just fails with React Native. I don't know what to do ideally. Remove performance optimizations from React Native is no go imho. I think it's not common to try assign false value into object, so I think your code can be fixed. Or I will have to maintain fork :-/

**Comment by tomatau** [comment]
Ahh ok - I agree, it's nicer to maintain React-native. Just not sure how we can prevent this from breaking without some sort of integration tests running through react-native now... which is a tad overkill.

Anyway, your code is pretty much how this logic was originally written, but then we started merging in falses to keep the code a bit cleaner and smaller.

Would you remove the parens? And then I'd be happy to merge.

**Comment by Hxucaa** [comment]
I encountered the same problem and came up with exactly the same fix. As I was about to submit a pull request, I found out someone already has. If only I had known earlier, I'd save couple hours debugging. XD

Anyway the fix is good.

**Comment by steida** [comment]
Parens are unnecessary, but I always favour explicit code over smart. Do you agree?

**Comment by tomatau** [comment]
I agree.

I don't see how unnecessary parens make something more explicit :) the parens make it look like it will evaluate to a boolean instead of just being a ternary.

**Comment by pburtchaell** [comment]
I released a fix for this in version 2.3.3 via #52. :100:

**Comment by steida** [comment]
Awesome. Thank you!

**Pull request closed without merging**
