### PR TITLE
Change serial actions dispatching example

### PR DESCRIPTION
**Pull request by yatsyk**
Completer example of multiple serial actions.
It not so clear how to perform async action in original example.

### CODE REVIEW

**Comment by tomatau** [comment]
There are plans to release a more comprehensive book of examples. I don't think adding this complexity in the main README is good for a first time user looking to work with this library.

Right now -- you can have a look at the tests to see how to get access to the dispatch function within a promise and have multiple serial actions.

https://github.com/pburtchaell/redux-promise-middleware/blob/master/test/index.spec.js#L347-L354

**Comment by yatsyk** [comment]
OK. Nice to hear about new examples.

Isn't it thunk middleware should be included for this test?

**Comment by tomatau** [comment]
The test uses a custom version of thunk that can give assertions on how it's being used by the promise-middleare. You can see it at the top where it exposes a spy property.

https://github.com/pburtchaell/redux-promise-middleware/blob/master/test/index.spec.js#L22-L29 :)

**Comment by yatsyk** [comment]
Thank you!

**Comment by tomatau** [comment]
I'm going to close this but please feel free to make a PR for some examples! We've been wanting more for a while but no-one has got around to doing them for a good few months now :)

**Comment by pburtchaell** [comment]
@yatsyk Just to note, the examples issue is #33 if you have an interest in helping out. Cheers!

**Pull request closed without merging**
