### PR TITLE
Add es6 module build

### PR DESCRIPTION
**Pull request by anajavi**
This PR adds building es6 module.

It allows webpack 3 to do scope hoisting, which saves a little space and gives little bit of performance.

### CODE REVIEW

**Comment by pburtchaell** [comment]
Thanks, this makes sense! Do you have an example of how this is done in other projects? I'm curious to see if there is a standard approach for this.

**Comment by anajavi** [comment]
Redux itself has same kind of build, made in these two commits:
https://github.com/reactjs/redux/commit/b27cb480bca24c0bff732370d6c2bfce4f894caa 
https://github.com/reactjs/redux/commit/13add05e4597ea961ded61a608c881924873bccc 

These also add "jsnext:main" to package.json, but I think that is superseded by "module". 

I mostly took this approach from this react-leaflet commit:
https://github.com/PaulLeCam/react-leaflet/commit/c4ef75799dcc155d45549096e0fd3db89070a58c

As most redux libraries like react-router-redux are now publishing es6 modules, they can be scope hoisted together.

**Comment by anajavi** [comment]
There actually might be a problem in the PR. Somehow the build seems to still transform to commonjs in es directory. I have to check it.

**Comment by anajavi** [comment]
I had to add all environments to .babelrc, the global presets didn't seem to merge after all.

**Comment by pburtchaell** [comment]
Great. Is everything good to go here @anajavi?

**Comment by anajavi** [comment]
It's good to go.

**Pull request merged**
