### PR TITLE
Version 3.0.0

### LINKED ISSUE #59: Don't swallow errors
It would be great to actually notify users on exceptions here: https://github.com/pburtchaell/redux-promise-middleware/blob/master/src/index.js#L54 vs recovering from the error.

At least a hook that logs rejections cleanly for debugging. Currently this is basically a:

    try {
        return [action, false] 
    } catch (e) {
        return [action, true]
    }

It would be useful to notify on rejections - maybe via taking a callback, so users don't get exceptions that are more silent by default.

### LINKED ISSUE #61: Bug when API payload has the same structure as an action
Not sure if this is actually a bug but I just came across this really edge-case-y thing where my API payload had the same structure like an action, which caused me a 3h headache why my promise never reached the `fulfilled` part, even though the API call was successfull.

My Action looks like this:

```
export const createCar = (data) => ({
  type: types.CREATE_CAR,
  payload: {
    promise: API.createCar(data)
  }
})
```

API:

```
API.createCar = function createCar(data) {
    return fetch(`${API_URL}/cars`, {
      method: 'POST',
      body: JSON.stringify(data)
    }).then((r) => r.json())
```

Reducer:

```
  ...

  [`${types.CREATE_CAR}_PENDING`]: (state) => {
    return {
      ...state,
      isPending: true
    }
  },

  [`${types.CREATE_CAR}_FULFILLED`]: (state, { payload }) => {
    return {
      ...state,
      isPending: false,
      data: {
        ...state.data,
        [payload.id]: payload
      }
    }
  },
  ...
```

Now I was wondering why my action never reached the 'fulfilled' state. This was because my API payload looked like this:

```
{
  id: 12345
  type: 'car',
  payload: {
    foo: 'bar',
    ...etc.
  }
}
```

What now happened is that this payload got fired as an action and it never reached the fulfilled state because of that.

I wonder if there is some way around that? currently I'm wrapping the api response in another object so it reaches the fulfilled state but I feel like this should not actually happen. It should always reach one of my pending...fulfilled...rejected states.

### PR DESCRIPTION
**Pull request by pburtchaell**
- Resolves #61
- Resolves #59

## Breaking Changes

This release introduces some major changes to the functionality of the middleware:

1. Middleware returns a promise instead of an action
2. The original promise is not returned, instead a new promise is created, which allows for `.then()` and `.catch()` to work as expected. 
3. Thunks are no longer bound to the promise 
4. Promises can be [explicitly or implicitly described](https://github.com/pburtchaell/redux-promise-middleware/blob/v3/docs/introduction.md) in the action object

All of these changes have come from my day-to-day use of the middleware in applications with lots of async code dealing with data access and network requests. 

For example, this is an action used to create a session using 2.0.0 API:

```js
function create(data) {
  return dispatch => {

    return dispatch({
      type: types.CREATE_SESSION,
      payload: {
        promise: session.create(data)
      }
    }).payload.promise.then(response => {
      if (!response.error) {
        dispatch(profile.getProfile()).payload.promise.then(response => {
          if (!response.error) dispatch(location.update('/'));
        });
      }
    });
  };
}
```

With the changes in 3.0.0, this code is more succinct.

```js
function create(data) {
  return dispatch => {

    return dispatch({
      type: types.CREATE_SESSION,
      payload: session.create(data)
    }).then(() => {
      dispatch(profile.getProfile()).then(() => {
        dispatch(location.update('/');
      });
    }).catch(e => /* handle error */);
  };
}
```

## Test Coverage

Most of the tests from the version 2.0.0 release are used.

```
  Redux Promise Middleware:
    ✓ must return a function to handle next
    When action is not a promise:
      ✓ invokes next with the action
      ✓ returns the return from next middleware
      ✓ does not dispatch any other actions
    When action has promise payload:
      ✓ dispatches a pending action for explicit promise payload
      ✓ dispatches a pending action for implicit promise payload
      ✓ pending action optionally contains optimistic update payload from data property
      ✓ pending action optionally contains meta property
      ✓ allows global customisation of action.type suffixes
      ✓ allows local customisation of action.type suffixes
    When promise is fulfilled:
      ✓ persists meta from original action
      ✓ returns value and action as parameters to `then()`
      ✓ allows global customisation of fulfilled action.type
      When resolve reason is null:
        ✓ resolved action.type dispatched
        ✓ returns null value
        ✓ action.payload is undefined
    When promise is rejected:
      ✓ persists meta from original action
      ✓ returns reason and action as parameters to `then()`
      ✓ allows errors to be handled with `catch()`
      ✓ allows global customisation of rejected action.type
      When reject reason is null:
        ✓ rejected action.type is dispatched
        ✓ returns null reason
        ✓ action.payload is undefined
```

## Other changes

Also worth noting:
1. There is [more documentation](https://github.com/pburtchaell/redux-promise-middleware/tree/v3/docs) (most topics covered are related to issues created) 
2. The example is functioning, but there is still more work that needs to be done there. I think it might be nice to have one complex example with React and Redux and a second more simple example with just Redux and no DOM library.
3. I have [an upgrade guide](https://github.com/pburtchaell/redux-promise-middleware/blob/v3/UPGRADING.md) for the transition from 2.0.0 to 3.0.0.

### CODE REVIEW

**Comment by pburtchaell** [comment]
@tomatau I'm curious to get your feedback here. Thanks. :smile:

**Comment by tomatau** [comment]
Hey - haven't had much chance to look but first thing, how would I change the meta value between the pending and fulfilled actions?

**Comment by chungeunkim** [comment]
@pburtchaell Hi, thanks for the major update. Do you have ETA for releasing this package via npm?

**Comment by pburtchaell** [comment]
@chungeunkim I am hoping to do it over the weekend. In the meantime, you should be able to [install this branch via npm](https://docs.npmjs.com/files/package.json#git-urls-as-dependencies).

**Comment by pburtchaell** [comment]
@tomatau 

> how would I change the meta value between the pending and fulfilled actions? e.g. I want a special meta value only for the fulfilled but not pending or rejected.

I had not thought of this, but perhaps the original action `meta` could have a specific model? For example:

```
// example with regular meta that is dispatched in each action (pending, fulfilled/rejected)
{
  type: 'FOO',
  meta: {
    // ...
  }
}

// example with meta for each action
{
  type: 'BAR',
  meta: {
    pending: {
      // meta properties for pending action
    },
    fulfilled: {
      // meta properties for fulfilled action
    }
  }
}
```

> how would I get at the optimistic action data (pending) from the place I originally call dispatch?

Can you give a use case/example? From what I am imagining, wouldn't theta already be available from where you call dispatch —since the data is probably being passed in as a parameter to the action?

```js
dispatch(myActionCreatorWithOptimisticData(data)) // data is available locally since it is passed in as arg
```

Perhaps I am misunderstanding your question.

**Comment by pburtchaell** [comment]
Hey @tomatau, further thoughts? I want to resolve your questions before I release. :smile:

**Comment by tomatau** [comment]
Hey sorry, been busy with other projects and doing Easter :)

Thanks for thinking about this one, another question though, what if say it was needed to conditionally change the meta? E.g. to broadcast only specific types of promise_rejections?

I think resolving a thunk was the most flexible solution for this kind of behaviour and also a nice place for side effects without wrapping the whole promise action in a thunk.

**Comment by pburtchaell** [comment]
I think what you are suggesting is good, so I am going to pull it into an issue for consideration in future modifications of the v3 API. For now, I'm going to merge and release this.

**Pull request merged**
