### PR TITLE
Tests for everything

### PR DESCRIPTION
**Pull request by tomatau**
This tests all the features we have right now that I could think of.

It also makes a fix for when the promise returns null, as I re-broke that in a previous commit.

So if this gets merged, can you republish a patch version.

### CODE REVIEW

**Comment by pburtchaell** [comment]
This is great. :+1:

**Comment by pburtchaell** [comment]
I released the patch as 2.3.1.

**Comment by tomatau** [comment]
Doesn't seem to be on npm yet

**Comment by pburtchaell** [comment]
Whoops. Sorry abut that. It should be now.

Just FYI, I ignored the tests and example directory on npm. I’m also in the process of setting up code coverage + https://coveralls.io <https://coveralls.io/>. I’ll probably finish that up in a couple of weeks when I have more time.

**Pull request merged**
