### PR TITLE
Use dispatch instead of next (fix #153)

### LINKED ISSUE #153: PENDING action not dispatched
## Version Number
4.2.0

## Code Example

```
const setVariable = (variable) => ({
  type: 'SET_VARIABLE',
  payload: new Promise(resolve => {
    setTimeout(() => {
      resolve(variable);
    }, 3000);
  }),
});
```

## Expected Behavior

See the following actions dispatched:
`SET_VARIABLE`, then `SET_VARIABLE_PENDING`, then after 3s, `SET_VARIABLE_FULLFILLED`

## Actual Behavior
`SET_VARIABLE`, then after 3s, `SET_VARIABLE_FULLFILLED`.

### PR DESCRIPTION
**Pull request by amaurymartiny**

### CODE REVIEW

**Comment by tomatau** [comment]
This might be a good idea to play the suffixed actions through the whole middleware stack instead of just the next actions. It could be a breaking change for some implementations though and the tests should reflect it.

Please add a test for this and I think it would be worth considering more pros and cons to this approach.

**Comment by pburtchaell** [comment]
I like the idea of exploring this. @amaurymartiny, can you update the PR with tests and a description that explains why this change is useful?

**Comment by amaurymartiny** [comment]
Unfortunately I won't have time now to dig deeper into this. Maybe in July, but not before. So if one of you guys wants to investigate it might be better.

**Comment by pburtchaell** [comment]
Alright, let's do this then: I'm going to close the PR and when you have time, @amaurymartiny, just reopen it and update the description with commentary on what this change will enable/fix.

**Pull request closed without merging**
