### PR TITLE
Remove deferred anti-pattern

### PR DESCRIPTION
**Pull request by benjamingr**
http://stackoverflow.com/questions/23803743/what-is-the-explicit-promise-construction-antipattern-and-how-do-i-avoid-it/23803744#23803744

### CODE REVIEW

**Comment by tomatau** [comment]
You're changing the original promise which we would rather pass through.

Have a look at the `v2` branch for an alternative solution to this problem.

**Comment by benjamingr** [comment]
Whenever you `then` a promise you're already returning a new promise. You're not "passing through" anyway when you `return new Promise`.

**Comment by pburtchaell** [comment]
I understand the crux of your argument, and while I would agree in other cases, I'm not sure the deferred promise anti-pattern would apply here. 

I would remember promises are state machines (that is, complex objects that hold a state). 

Here, the promise returned by the `request` function holds the the state of one HTTP request. There are four possible outcomes (or "[settled](https://github.com/domenic/promises-unwrapping/blob/master/docs/states-and-fates.md)") states for this promise:

1. **Rejected:** the server sent an erroneous response
2. **Rejected:** the request is missing `url` parameter
3. **Rejected:** the request is missing`options` parameter
4. **Fulfilled:** the server sent a successful, 200 OK, response

---

Currently, the request function returns one promise that can vary to describe each of these outcomes. 

You have proposed that the request function should return one of three promises, each describing a different outcome. To break this down:

```js
// possible Promise #1 that could be returned
if (!url) return Promise.reject(...) 

) // possible Promise #2 that could be returned
if (!options) return Promise.reject(...)

// possible Promise #3  that could be returned
return fetch(...) 
```

With this proposed change, the promise doesn't describing the state of the _entire_ request, but rather, parts of the request. 

---

In the end, I don't really see one as being objectively better than the other, but in terms of syntax and my mental model of the code, I would prefer the original solution. 

And for what it's worth, this is just an example. There is a lot of code missing that one might normally use in production.

**Comment by tomatau** [comment]
> Whenever you then a promise you're already returning a new promise. You're not "passing through" anyway when you return new Promise.

I'm not saying anything contrary to this. Also I pointed out the v2 branch for an alternative solution but I guess you didn't going from what you said.

**Comment by benjamingr** [comment]
>  I'm not sure the deferred promise anti-pattern would apply here.

It definitely does. You're wrapping a promise with another promise manually and manually taking care of all edge cases. 

> You have proposed that the request function should return one of three promises, each describing a different outcome. To break this down

A promise itself is just the value it resolves to. The fact it's "three different promises" is mostly irrelevant.

> In the end, I don't really see one as being objectively better than the other

Your library - your call. I'd probably opt for:

```js
export default async (url, options) => { 
  if(!url) throw new Error("URL parameter required")
  if(!options) throw new Error("Options parameter required")
  const response = await fetch(url, options).then(x => x.json());
  if(response.errors) throw response.errors; // todo: wrap in real error
  return response;
};
```

**Comment by benjamingr** [comment]
@pburtchaell hey was this fixed?

**Pull request closed without merging**
